# file names
# mackerel 1
# 전부 개별 list에 day가 index임
#
# mackerel 2, 3
# 한개에  stage별로 list를 나눔
# ex) 해당 케이스의 case[0][1] 이면 스테이지0의 2번째 물고기

# =======================================================      mackerel 1      =======================================================

mackerel1_stop_eye_brigt = [["source/mackerel#1/stop/0d/eye/1-bright.jpg",
                             "source/mackerel#1/stop/0d/eye/2-bright.jpg",
                             "source/mackerel#1/stop/0d/eye/3-bright.jpg",
                             "source/mackerel#1/stop/0d/eye/4-bright.jpg",
                             "source/mackerel#1/stop/0d/eye/5-bright.jpg"],
                            ["source/mackerel#1/stop/1d/eye/1-bright.jpg",
                             "source/mackerel#1/stop/1d/eye/2-bright.jpg",
                             "source/mackerel#1/stop/1d/eye/3-bright.jpg",
                             "source/mackerel#1/stop/1d/eye/4-bright.jpg",
                             "source/mackerel#1/stop/1d/eye/5-bright.jpg"],
                            ["source/mackerel#1/stop/2d/eye/1-bright.jpg",
                             "source/mackerel#1/stop/2d/eye/2-bright.jpg",
                             "source/mackerel#1/stop/2d/eye/3-bright.jpg",
                             "source/mackerel#1/stop/2d/eye/4-bright.jpg",
                             "source/mackerel#1/stop/2d/eye/5-bright.jpg"],
                            ["source/mackerel#1/stop/3d/eye/1-bright.jpg",
                             "source/mackerel#1/stop/3d/eye/2-bright.jpg",
                             "source/mackerel#1/stop/3d/eye/3-bright.jpg",
                             "source/mackerel#1/stop/3d/eye/4-bright.jpg",
                             "source/mackerel#1/stop/3d/eye/5-bright.jpg"],
                            ["source/mackerel#1/stop/4d/eye/1-bright.jpg",
                             "source/mackerel#1/stop/4d/eye/2-bright.jpg",
                             "source/mackerel#1/stop/4d/eye/3-bright.jpg",
                             "source/mackerel#1/stop/4d/eye/4-bright.jpg",
                             "source/mackerel#1/stop/4d/eye/5-bright.jpg"],
                            ["source/mackerel#1/stop/5d/eye/1-bright.jpg",
                             "source/mackerel#1/stop/5d/eye/2-bright.jpg",
                             "source/mackerel#1/stop/5d/eye/3-bright.jpg",
                             "source/mackerel#1/stop/5d/eye/4-bright.jpg",
                             "source/mackerel#1/stop/5d/eye/5-bright.jpg"],
                            ["source/mackerel#1/stop/6d/eye/1-bright.jpg",
                             "source/mackerel#1/stop/6d/eye/2-bright.jpg",
                             "source/mackerel#1/stop/6d/eye/3-bright.jpg",
                             "source/mackerel#1/stop/6d/eye/4-bright.jpg",
                             "source/mackerel#1/stop/6d/eye/5-bright.jpg"],
                            ["source/mackerel#1/stop/7d/eye/1-bright.jpg",
                             "source/mackerel#1/stop/7d/eye/2-bright.jpg",
                             "source/mackerel#1/stop/7d/eye/3-bright.jpg",
                             "source/mackerel#1/stop/7d/eye/4-bright.jpg",
                             "source/mackerel#1/stop/7d/eye/5-bright.jpg"],
                            ["source/mackerel#1/stop/8d/eye/1-bright.jpg",
                             "source/mackerel#1/stop/8d/eye/2-bright.jpg",
                             "source/mackerel#1/stop/8d/eye/3-bright.jpg",
                             "source/mackerel#1/stop/8d/eye/4-bright.jpg",
                             "source/mackerel#1/stop/8d/eye/5-bright.jpg"],
                            ["source/mackerel#1/stop/9d/eye/1-bright.jpg",
                             "source/mackerel#1/stop/9d/eye/2-bright.jpg",
                             "source/mackerel#1/stop/9d/eye/3-bright.jpg",
                             "source/mackerel#1/stop/9d/eye/4-bright.jpg",
                             "source/mackerel#1/stop/9d/eye/5-bright.jpg"],
                            ["source/mackerel#1/stop/10d/eye/1-bright.jpg",
                             "source/mackerel#1/stop/10d/eye/2-bright.jpg",
                             "source/mackerel#1/stop/10d/eye/3-bright.jpg",
                             "source/mackerel#1/stop/10d/eye/4-bright.jpg",
                             "source/mackerel#1/stop/10d/eye/5-bright.jpg"],
                            ["source/mackerel#1/stop/11d/eye/1-bright.jpg",
                             "source/mackerel#1/stop/11d/eye/2-bright.jpg",
                             "source/mackerel#1/stop/11d/eye/3-bright.jpg",
                             "source/mackerel#1/stop/11d/eye/4-bright.jpg",
                             "source/mackerel#1/stop/11d/eye/5-bright.jpg"]
                            ]

mackerel1_stop_eye_dark = [["source/mackerel#1/stop/0d/eye/1-dark.jpg",
                            "source/mackerel#1/stop/0d/eye/2-dark.jpg",
                            "source/mackerel#1/stop/0d/eye/3-dark.jpg",
                            "source/mackerel#1/stop/0d/eye/4-dark.jpg",
                            "source/mackerel#1/stop/0d/eye/5-dark.jpg"],
                           ["source/mackerel#1/stop/1d/eye/1-dark.jpg",
                            "source/mackerel#1/stop/1d/eye/2-dark.jpg",
                            "source/mackerel#1/stop/1d/eye/3-dark.jpg",
                            "source/mackerel#1/stop/1d/eye/4-dark.jpg",
                            "source/mackerel#1/stop/1d/eye/5-dark.jpg"],
                           ["source/mackerel#1/stop/2d/eye/1-dark.jpg",
                            "source/mackerel#1/stop/2d/eye/2-dark.jpg",
                            "source/mackerel#1/stop/2d/eye/3-dark.jpg",
                            "source/mackerel#1/stop/2d/eye/4-dark.jpg",
                            "source/mackerel#1/stop/2d/eye/5-dark.jpg"],
                           ["source/mackerel#1/stop/3d/eye/1-dark.jpg",
                            "source/mackerel#1/stop/3d/eye/2-dark.jpg",
                            "source/mackerel#1/stop/3d/eye/3-dark.jpg",
                            "source/mackerel#1/stop/3d/eye/4-dark.jpg",
                            "source/mackerel#1/stop/3d/eye/5-dark.jpg"],
                           ["source/mackerel#1/stop/4d/eye/1-dark.jpg",
                            "source/mackerel#1/stop/4d/eye/2-dark.jpg",
                            "source/mackerel#1/stop/4d/eye/3-dark.jpg",
                            "source/mackerel#1/stop/4d/eye/4-dark.jpg",
                            "source/mackerel#1/stop/4d/eye/5-dark.jpg"],
                           ["source/mackerel#1/stop/5d/eye/1-dark.jpg",
                            "source/mackerel#1/stop/5d/eye/2-dark.jpg",
                            "source/mackerel#1/stop/5d/eye/3-dark.jpg",
                            "source/mackerel#1/stop/5d/eye/4-dark.jpg",
                            "source/mackerel#1/stop/5d/eye/5-dark.jpg"],
                           ["source/mackerel#1/stop/6d/eye/1-dark.jpg",
                            "source/mackerel#1/stop/6d/eye/2-dark.jpg",
                            "source/mackerel#1/stop/6d/eye/3-dark.jpg",
                            "source/mackerel#1/stop/6d/eye/4-dark.jpg",
                            "source/mackerel#1/stop/6d/eye/5-dark.jpg"],
                           ["source/mackerel#1/stop/7d/eye/1-dark.jpg",
                            "source/mackerel#1/stop/7d/eye/2-dark.jpg",
                            "source/mackerel#1/stop/7d/eye/3-dark.jpg",
                            "source/mackerel#1/stop/7d/eye/4-dark.jpg",
                            "source/mackerel#1/stop/7d/eye/5-dark.jpg"],
                           ["source/mackerel#1/stop/8d/eye/1-dark.jpg",
                            "source/mackerel#1/stop/8d/eye/2-dark.jpg",
                            "source/mackerel#1/stop/8d/eye/3-dark.jpg",
                            "source/mackerel#1/stop/8d/eye/4-dark.jpg",
                            "source/mackerel#1/stop/8d/eye/5-dark.jpg"],
                           ["source/mackerel#1/stop/9d/eye/1-dark.jpg",
                            "source/mackerel#1/stop/9d/eye/2-dark.jpg",
                            "source/mackerel#1/stop/9d/eye/3-dark.jpg",
                            "source/mackerel#1/stop/9d/eye/4-dark.jpg",
                            "source/mackerel#1/stop/9d/eye/5-dark.jpg"],
                           ["source/mackerel#1/stop/10d/eye/1-dark.jpg",
                            "source/mackerel#1/stop/10d/eye/2-dark.jpg",
                            "source/mackerel#1/stop/10d/eye/3-dark.jpg",
                            "source/mackerel#1/stop/10d/eye/4-dark.jpg",
                            "source/mackerel#1/stop/10d/eye/5-dark.jpg"],
                           ["source/mackerel#1/stop/11d/eye/1-dark.jpg",
                            "source/mackerel#1/stop/11d/eye/2-dark.jpg",
                            "source/mackerel#1/stop/11d/eye/3-dark.jpg",
                            "source/mackerel#1/stop/11d/eye/4-dark.jpg",
                            "source/mackerel#1/stop/11d/eye/5-dark.jpg"]
                           ]

mackerel1_stop_gill_brigt = [["source/mackerel#1/stop/0d/gill/1-bright.jpg",
                              "source/mackerel#1/stop/0d/gill/2-bright.jpg",
                              "source/mackerel#1/stop/0d/gill/3-bright.jpg",
                              "source/mackerel#1/stop/0d/gill/4-bright.jpg",
                              "source/mackerel#1/stop/0d/gill/5-bright.jpg"],
                             ["source/mackerel#1/stop/1d/gill/1-bright.jpg",
                              "source/mackerel#1/stop/1d/gill/2-bright.jpg",
                              "source/mackerel#1/stop/1d/gill/3-bright.jpg",
                              "source/mackerel#1/stop/1d/gill/4-bright.jpg",
                              "source/mackerel#1/stop/1d/gill/5-bright.jpg"],
                             ["source/mackerel#1/stop/2d/gill/1-bright.jpg",
                              "source/mackerel#1/stop/2d/gill/2-bright.jpg",
                              "source/mackerel#1/stop/2d/gill/3-bright.jpg",
                              "source/mackerel#1/stop/2d/gill/4-bright.jpg",
                              "source/mackerel#1/stop/2d/gill/5-bright.jpg"],
                             ["source/mackerel#1/stop/3d/gill/1-bright.jpg",
                              "source/mackerel#1/stop/3d/gill/2-bright.jpg",
                              "source/mackerel#1/stop/3d/gill/3-bright.jpg",
                              "source/mackerel#1/stop/3d/gill/4-bright.jpg",
                              "source/mackerel#1/stop/3d/gill/5-bright.jpg"],
                             ["source/mackerel#1/stop/4d/gill/1-bright.jpg",
                              "source/mackerel#1/stop/4d/gill/2-bright.jpg",
                              "source/mackerel#1/stop/4d/gill/3-bright.jpg",
                              "source/mackerel#1/stop/4d/gill/4-bright.jpg",
                              "source/mackerel#1/stop/4d/gill/5-bright.jpg"],
                             ["source/mackerel#1/stop/5d/gill/1-bright.jpg",
                              "source/mackerel#1/stop/5d/gill/2-bright.jpg",
                              "source/mackerel#1/stop/5d/gill/3-bright.jpg",
                              "source/mackerel#1/stop/5d/gill/4-bright.jpg",
                              "source/mackerel#1/stop/5d/gill/5-bright.jpg"],
                             ["source/mackerel#1/stop/6d/gill/1-bright.jpg",
                              "source/mackerel#1/stop/6d/gill/2-bright.jpg",
                              "source/mackerel#1/stop/6d/gill/3-bright.jpg",
                              "source/mackerel#1/stop/6d/gill/4-bright.jpg",
                              "source/mackerel#1/stop/6d/gill/5-bright.jpg"],
                             ["source/mackerel#1/stop/7d/gill/1-bright.jpg",
                              "source/mackerel#1/stop/7d/gill/2-bright.jpg",
                              "source/mackerel#1/stop/7d/gill/3-bright.jpg",
                              "source/mackerel#1/stop/7d/gill/4-bright.jpg",
                              "source/mackerel#1/stop/7d/gill/5-bright.jpg"],
                             ["source/mackerel#1/stop/8d/gill/1-bright.jpg",
                              "source/mackerel#1/stop/8d/gill/2-bright.jpg",
                              "source/mackerel#1/stop/8d/gill/3-bright.jpg",
                              "source/mackerel#1/stop/8d/gill/4-bright.jpg",
                              "source/mackerel#1/stop/8d/gill/5-bright.jpg"],
                             ["source/mackerel#1/stop/9d/gill/1-bright.jpg",
                              "source/mackerel#1/stop/9d/gill/2-bright.jpg",
                              "source/mackerel#1/stop/9d/gill/3-bright.jpg",
                              "source/mackerel#1/stop/9d/gill/4-bright.jpg",
                              "source/mackerel#1/stop/9d/gill/5-bright.jpg"],
                             ["source/mackerel#1/stop/10d/gill/1-bright.jpg",
                              "source/mackerel#1/stop/10d/gill/2-bright.jpg",
                              "source/mackerel#1/stop/10d/gill/3-bright.jpg",
                              "source/mackerel#1/stop/10d/gill/4-bright.jpg",
                              "source/mackerel#1/stop/10d/gill/5-bright.jpg"],
                             ["source/mackerel#1/stop/11d/gill/1-bright.jpg",
                              "source/mackerel#1/stop/11d/gill/2-bright.jpg",
                              "source/mackerel#1/stop/11d/gill/3-bright.jpg",
                              "source/mackerel#1/stop/11d/gill/4-bright.jpg",
                              "source/mackerel#1/stop/11d/gill/5-bright.jpg"]
                             ]

mackerel1_stop_gill_dark = [["source/mackerel#1/stop/0d/gill/1-dark.jpg",
                             "source/mackerel#1/stop/0d/gill/2-dark.jpg",
                             "source/mackerel#1/stop/0d/gill/3-dark.jpg",
                             "source/mackerel#1/stop/0d/gill/4-dark.jpg",
                             "source/mackerel#1/stop/0d/gill/5-dark.jpg"],
                            ["source/mackerel#1/stop/1d/gill/1-dark.jpg",
                             "source/mackerel#1/stop/1d/gill/2-dark.jpg",
                             "source/mackerel#1/stop/1d/gill/3-dark.jpg",
                             "source/mackerel#1/stop/1d/gill/4-dark.jpg",
                             "source/mackerel#1/stop/1d/gill/5-dark.jpg"],
                            ["source/mackerel#1/stop/2d/gill/1-dark.jpg",
                             "source/mackerel#1/stop/2d/gill/2-dark.jpg",
                             "source/mackerel#1/stop/2d/gill/3-dark.jpg",
                             "source/mackerel#1/stop/2d/gill/4-dark.jpg",
                             "source/mackerel#1/stop/2d/gill/5-dark.jpg"],
                            ["source/mackerel#1/stop/3d/gill/1-dark.jpg",
                             "source/mackerel#1/stop/3d/gill/2-dark.jpg",
                             "source/mackerel#1/stop/3d/gill/3-dark.jpg",
                             "source/mackerel#1/stop/3d/gill/4-dark.jpg",
                             "source/mackerel#1/stop/3d/gill/5-dark.jpg"],
                            ["source/mackerel#1/stop/4d/gill/1-dark.jpg",
                             "source/mackerel#1/stop/4d/gill/2-dark.jpg",
                             "source/mackerel#1/stop/4d/gill/3-dark.jpg",
                             "source/mackerel#1/stop/4d/gill/4-dark.jpg",
                             "source/mackerel#1/stop/4d/gill/5-dark.jpg"],
                            ["source/mackerel#1/stop/5d/gill/1-dark.jpg",
                             "source/mackerel#1/stop/5d/gill/2-dark.jpg",
                             "source/mackerel#1/stop/5d/gill/3-dark.jpg",
                             "source/mackerel#1/stop/5d/gill/4-dark.jpg",
                             "source/mackerel#1/stop/5d/gill/5-dark.jpg"],
                            ["source/mackerel#1/stop/6d/gill/1-dark.jpg",
                             "source/mackerel#1/stop/6d/gill/2-dark.jpg",
                             "source/mackerel#1/stop/6d/gill/3-dark.jpg",
                             "source/mackerel#1/stop/6d/gill/4-dark.jpg",
                             "source/mackerel#1/stop/6d/gill/5-dark.jpg"],
                            ["source/mackerel#1/stop/7d/gill/1-dark.jpg",
                             "source/mackerel#1/stop/7d/gill/2-dark.jpg",
                             "source/mackerel#1/stop/7d/gill/3-dark.jpg",
                             "source/mackerel#1/stop/7d/gill/4-dark.jpg",
                             "source/mackerel#1/stop/7d/gill/5-dark.jpg"],
                            ["source/mackerel#1/stop/8d/gill/1-dark.jpg",
                             "source/mackerel#1/stop/8d/gill/2-dark.jpg",
                             "source/mackerel#1/stop/8d/gill/3-dark.jpg",
                             "source/mackerel#1/stop/8d/gill/4-dark.jpg",
                             "source/mackerel#1/stop/8d/gill/5-dark.jpg"],
                            ["source/mackerel#1/stop/9d/gill/1-dark.jpg",
                             "source/mackerel#1/stop/9d/gill/2-dark.jpg",
                             "source/mackerel#1/stop/9d/gill/3-dark.jpg",
                             "source/mackerel#1/stop/9d/gill/4-dark.jpg",
                             "source/mackerel#1/stop/9d/gill/5-dark.jpg"],
                            ["source/mackerel#1/stop/10d/gill/1-dark.jpg",
                             "source/mackerel#1/stop/10d/gill/2-dark.jpg",
                             "source/mackerel#1/stop/10d/gill/3-dark.jpg",
                             "source/mackerel#1/stop/10d/gill/4-dark.jpg",
                             "source/mackerel#1/stop/10d/gill/5-dark.jpg"],
                            ["source/mackerel#1/stop/11d/gill/1-dark.jpg",
                             "source/mackerel#1/stop/11d/gill/2-dark.jpg",
                             "source/mackerel#1/stop/11d/gill/3-dark.jpg",
                             "source/mackerel#1/stop/11d/gill/4-dark.jpg",
                             "source/mackerel#1/stop/11d/gill/5-dark.jpg"]
                            ]

mackerel1_continue_eye_bright = [["source/mackerel#1/continue/a/0d-bright.jpg",
                                  "source/mackerel#1/continue/b/0d-bright.jpg",
                                  "source/mackerel#1/continue/c/0d-bright.jpg",
                                  "source/mackerel#1/continue/d/0d-bright.jpg",
                                  "source/mackerel#1/continue/e/0d-bright.jpg"],
                                 ["source/mackerel#1/continue/a/1d-bright.jpg",
                                  "source/mackerel#1/continue/b/1d-bright.jpg",
                                  "source/mackerel#1/continue/c/1d-bright.jpg",
                                  "source/mackerel#1/continue/d/1d-bright.jpg",
                                  "source/mackerel#1/continue/e/1d-bright.jpg"],
                                 ["source/mackerel#1/continue/a/2d-bright.jpg",
                                  "source/mackerel#1/continue/b/2d-bright.jpg",
                                  "source/mackerel#1/continue/c/2d-bright.jpg",
                                  "source/mackerel#1/continue/d/2d-bright.jpg",
                                  "source/mackerel#1/continue/e/2d-bright.jpg"],
                                 ["source/mackerel#1/continue/a/3d-bright.jpg",
                                  "source/mackerel#1/continue/b/3d-bright.jpg",
                                  "source/mackerel#1/continue/c/3d-bright.jpg",
                                  "source/mackerel#1/continue/d/3d-bright.jpg",
                                  "source/mackerel#1/continue/e/3d-bright.jpg"],
                                 ["source/mackerel#1/continue/a/4d-bright.jpg",
                                  "source/mackerel#1/continue/b/4d-bright.jpg",
                                  "source/mackerel#1/continue/c/4d-bright.jpg",
                                  "source/mackerel#1/continue/d/4d-bright.jpg",
                                  "source/mackerel#1/continue/e/4d-bright.jpg"],
                                 ["source/mackerel#1/continue/a/5d-bright.jpg",
                                  "source/mackerel#1/continue/b/5d-bright.jpg",
                                  "source/mackerel#1/continue/c/5d-bright.jpg",
                                  "source/mackerel#1/continue/d/5d-bright.jpg",
                                  "source/mackerel#1/continue/e/5d-bright.jpg"],
                                 ["source/mackerel#1/continue/a/6d-bright.jpg",
                                  "source/mackerel#1/continue/b/6d-bright.jpg",
                                  "source/mackerel#1/continue/c/6d-bright.jpg",
                                  "source/mackerel#1/continue/d/6d-bright.jpg",
                                  "source/mackerel#1/continue/e/6d-bright.jpg"],
                                 ["source/mackerel#1/continue/a/7d-bright.jpg",
                                  "source/mackerel#1/continue/b/7d-bright.jpg",
                                  "source/mackerel#1/continue/c/7d-bright.jpg",
                                  "source/mackerel#1/continue/d/7d-bright.jpg",
                                  "source/mackerel#1/continue/e/7d-bright.jpg"],
                                 ["source/mackerel#1/continue/a/8d-bright.jpg",
                                  "source/mackerel#1/continue/b/8d-bright.jpg",
                                  "source/mackerel#1/continue/c/8d-bright.jpg",
                                  "source/mackerel#1/continue/d/8d-bright.jpg",
                                  "source/mackerel#1/continue/e/8d-bright.jpg"],
                                 ["source/mackerel#1/continue/a/9d-bright.jpg",
                                  "source/mackerel#1/continue/b/9d-bright.jpg",
                                  "source/mackerel#1/continue/c/9d-bright.jpg",
                                  "source/mackerel#1/continue/d/9d-bright.jpg",
                                  "source/mackerel#1/continue/e/9d-bright.jpg"],
                                 ["source/mackerel#1/continue/a/10d-bright.jpg",
                                  "source/mackerel#1/continue/b/10d-bright.jpg",
                                  "source/mackerel#1/continue/c/10d-bright.jpg",
                                  "source/mackerel#1/continue/d/10d-bright.jpg",
                                  "source/mackerel#1/continue/e/10d-bright.jpg"],
                                 ["source/mackerel#1/continue/a/11d-bright.jpg",
                                  "source/mackerel#1/continue/b/11d-bright.jpg",
                                  "source/mackerel#1/continue/c/11d-bright.jpg",
                                  "source/mackerel#1/continue/d/11d-bright.jpg",
                                  "source/mackerel#1/continue/e/11d-bright.jpg"]
                                 ]

mackerel1_continue_eye_dark = [["source/mackerel#1/continue/a/0d-dark.jpg",
                                "source/mackerel#1/continue/b/0d-dark.jpg",
                                "source/mackerel#1/continue/c/0d-dark.jpg",
                                "source/mackerel#1/continue/d/0d-dark.jpg",
                                "source/mackerel#1/continue/e/0d-dark.jpg"],
                               ["source/mackerel#1/continue/a/1d-dark.jpg",
                                "source/mackerel#1/continue/b/1d-dark.jpg",
                                "source/mackerel#1/continue/c/1d-dark.jpg",
                                "source/mackerel#1/continue/d/1d-dark.jpg",
                                "source/mackerel#1/continue/e/1d-dark.jpg"],
                               ["source/mackerel#1/continue/a/2d-dark.jpg",
                                "source/mackerel#1/continue/b/2d-dark.jpg",
                                "source/mackerel#1/continue/c/2d-dark.jpg",
                                "source/mackerel#1/continue/d/2d-dark.jpg",
                                "source/mackerel#1/continue/e/2d-dark.jpg"],
                               ["source/mackerel#1/continue/a/3d-dark.jpg",
                                "source/mackerel#1/continue/b/3d-dark.jpg",
                                "source/mackerel#1/continue/c/3d-dark.jpg",
                                "source/mackerel#1/continue/d/3d-dark.jpg",
                                "source/mackerel#1/continue/e/3d-dark.jpg"],
                               ["source/mackerel#1/continue/a/4d-dark.jpg",
                                "source/mackerel#1/continue/b/4d-dark.jpg",
                                "source/mackerel#1/continue/c/4d-dark.jpg",
                                "source/mackerel#1/continue/d/4d-dark.jpg",
                                "source/mackerel#1/continue/e/4d-dark.jpg"],
                               ["source/mackerel#1/continue/a/5d-dark.jpg",
                                "source/mackerel#1/continue/b/5d-dark.jpg",
                                "source/mackerel#1/continue/c/5d-dark.jpg",
                                "source/mackerel#1/continue/d/5d-dark.jpg",
                                "source/mackerel#1/continue/e/5d-dark.jpg"],
                               ["source/mackerel#1/continue/a/6d-dark.jpg",
                                "source/mackerel#1/continue/b/6d-dark.jpg",
                                "source/mackerel#1/continue/c/6d-dark.jpg",
                                "source/mackerel#1/continue/d/6d-dark.jpg",
                                "source/mackerel#1/continue/e/6d-dark.jpg"],
                               ["source/mackerel#1/continue/a/7d-dark.jpg",
                                "source/mackerel#1/continue/b/7d-dark.jpg",
                                "source/mackerel#1/continue/c/7d-dark.jpg",
                                "source/mackerel#1/continue/d/7d-dark.jpg",
                                "source/mackerel#1/continue/e/7d-dark.jpg"],
                               ["source/mackerel#1/continue/a/8d-dark.jpg",
                                "source/mackerel#1/continue/b/8d-dark.jpg",
                                "source/mackerel#1/continue/c/8d-dark.jpg",
                                "source/mackerel#1/continue/d/8d-dark.jpg",
                                "source/mackerel#1/continue/e/8d-dark.jpg"],
                               ["source/mackerel#1/continue/a/9d-dark.jpg",
                                "source/mackerel#1/continue/b/9d-dark.jpg",
                                "source/mackerel#1/continue/c/9d-dark.jpg",
                                "source/mackerel#1/continue/d/9d-dark.jpg",
                                "source/mackerel#1/continue/e/9d-dark.jpg"],
                               ["source/mackerel#1/continue/a/10d-dark.jpg",
                                "source/mackerel#1/continue/b/10d-dark.jpg",
                                "source/mackerel#1/continue/c/10d-dark.jpg",
                                "source/mackerel#1/continue/d/10d-dark.jpg",
                                "source/mackerel#1/continue/e/10d-dark.jpg"],
                               ["source/mackerel#1/continue/a/11d-dark.jpg",
                                "source/mackerel#1/continue/b/11d-dark.jpg",
                                "source/mackerel#1/continue/c/11d-dark.jpg",
                                "source/mackerel#1/continue/d/11d-dark.jpg",
                                "source/mackerel#1/continue/e/11d-dark.jpg"]
                               ]

# =======================================================      mackerel 2      =======================================================

mackerel2_250_back_bright = [["source/mackerel#2/stage00/250/back/bright/01.png",
                              "source/mackerel#2/stage00/250/back/bright/02.png",
                              "source/mackerel#2/stage00/250/back/bright/03.png",
                              "source/mackerel#2/stage00/250/back/bright/04.png",
                              "source/mackerel#2/stage00/250/back/bright/05.png"],
                             ["source/mackerel#2/stage01/250/back/bright/01.png",
                              "source/mackerel#2/stage01/250/back/bright/02.png",
                              "source/mackerel#2/stage01/250/back/bright/03.png",
                              "source/mackerel#2/stage01/250/back/bright/04.png",
                              "source/mackerel#2/stage01/250/back/bright/05.png"]]

mackerel2_250_back_dark = [["source/mackerel#2/stage00/250/back/dark/01.png",
                            "source/mackerel#2/stage00/250/back/dark/02.png",
                            "source/mackerel#2/stage00/250/back/dark/03.png",
                            "source/mackerel#2/stage00/250/back/dark/04.png",
                            "source/mackerel#2/stage00/250/back/dark/05.png"],
                           ["source/mackerel#2/stage01/250/back/dark/01.png",
                            "source/mackerel#2/stage01/250/back/dark/02.png",
                            "source/mackerel#2/stage01/250/back/dark/03.png",
                            "source/mackerel#2/stage01/250/back/dark/04.png",
                            "source/mackerel#2/stage01/250/back/dark/05.png"]]

mackerel2_350_back_bright = [["source/mackerel#2/stage00/350/back/bright/01.png",
                              "source/mackerel#2/stage00/350/back/bright/02.png",
                              "source/mackerel#2/stage00/350/back/bright/03.png",
                              "source/mackerel#2/stage00/350/back/bright/04.png",
                              "source/mackerel#2/stage00/350/back/bright/05.png"],
                             ["source/mackerel#2/stage01/350/back/bright/01.png",
                              "source/mackerel#2/stage01/350/back/bright/02.png",
                              "source/mackerel#2/stage01/350/back/bright/03.png",
                              "source/mackerel#2/stage01/350/back/bright/04.png",
                              "source/mackerel#2/stage01/350/back/bright/05.png"]]

mackerel2_350_back_dark = [["source/mackerel#2/stage00/350/back/dark/01.png",
                            "source/mackerel#2/stage00/350/back/dark/02.png",
                            "source/mackerel#2/stage00/350/back/dark/03.png",
                            "source/mackerel#2/stage00/350/back/dark/04.png",
                            "source/mackerel#2/stage00/350/back/dark/05.png"],
                           ["source/mackerel#2/stage01/350/back/dark/01.png",
                            "source/mackerel#2/stage01/350/back/dark/02.png",
                            "source/mackerel#2/stage01/350/back/dark/03.png",
                            "source/mackerel#2/stage01/350/back/dark/04.png",
                            "source/mackerel#2/stage01/350/back/dark/05.png"]]

mackerel2_250_stomach_bright = [["source/mackerel#2/stage00/250/stomach/bright/01.png",
                                 "source/mackerel#2/stage00/250/stomach/bright/02.png",
                                 "source/mackerel#2/stage00/250/stomach/bright/03.png",
                                 "source/mackerel#2/stage00/250/stomach/bright/04.png",
                                 "source/mackerel#2/stage00/250/stomach/bright/05.png"],
                                ["source/mackerel#2/stage01/250/stomach/bright/01.png",
                                 "source/mackerel#2/stage01/250/stomach/bright/02.png",
                                 "source/mackerel#2/stage01/250/stomach/bright/03.png",
                                 "source/mackerel#2/stage01/250/stomach/bright/04.png",
                                 "source/mackerel#2/stage01/250/stomach/bright/05.png"]]

mackerel2_250_stomach_dark = [["source/mackerel#2/stage00/250/stomach/dark/01.png",
                               "source/mackerel#2/stage00/250/stomach/dark/02.png",
                               "source/mackerel#2/stage00/250/stomach/dark/03.png",
                               "source/mackerel#2/stage00/250/stomach/dark/04.png",
                               "source/mackerel#2/stage00/250/stomach/dark/05.png"],
                              ["source/mackerel#2/stage01/250/stomach/dark/01.png",
                               "source/mackerel#2/stage01/250/stomach/dark/02.png",
                               "source/mackerel#2/stage01/250/stomach/dark/03.png",
                               "source/mackerel#2/stage01/250/stomach/dark/04.png",
                               "source/mackerel#2/stage01/250/stomach/dark/05.png"]]

mackerel2_350_stomach_bright = [["source/mackerel#2/stage00/350/stomach/bright/01.png",
                                 "source/mackerel#2/stage00/350/stomach/bright/02.png",
                                 "source/mackerel#2/stage00/350/stomach/bright/03.png",
                                 "source/mackerel#2/stage00/350/stomach/bright/04.png",
                                 "source/mackerel#2/stage00/350/stomach/bright/05.png"],
                                ["source/mackerel#2/stage01/350/stomach/bright/01.png",
                                 "source/mackerel#2/stage01/350/stomach/bright/02.png",
                                 "source/mackerel#2/stage01/350/stomach/bright/03.png",
                                 "source/mackerel#2/stage01/350/stomach/bright/04.png",
                                 "source/mackerel#2/stage01/350/stomach/bright/05.png"]]

mackerel2_350_stomach_dark = [["source/mackerel#2/stage00/350/stomach/dark/01.png",
                               "source/mackerel#2/stage00/350/stomach/dark/02.png",
                               "source/mackerel#2/stage00/350/stomach/dark/03.png",
                               "source/mackerel#2/stage00/350/stomach/dark/04.png",
                               "source/mackerel#2/stage00/350/stomach/dark/05.png"],
                              ["source/mackerel#2/stage01/350/stomach/dark/01.png",
                               "source/mackerel#2/stage01/350/stomach/dark/02.png",
                               "source/mackerel#2/stage01/350/stomach/dark/03.png",
                               "source/mackerel#2/stage01/350/stomach/dark/04.png",
                               "source/mackerel#2/stage01/350/stomach/dark/05.png"]]

# =======================================================      mackerel 3      =======================================================

mackerel3_250_back_bright = [["source/mackerel#3/stage00/250/back/bright/01.png",
                              "source/mackerel#3/stage00/250/back/bright/02.png",
                              "source/mackerel#3/stage00/250/back/bright/03.png",
                              "source/mackerel#3/stage00/250/back/bright/04.png",
                              "source/mackerel#3/stage00/250/back/bright/05.png"],
                             ["source/mackerel#3/stage01/250/back/bright/01.png",
                              "source/mackerel#3/stage01/250/back/bright/02.png",
                              "source/mackerel#3/stage01/250/back/bright/03.png",
                              "source/mackerel#3/stage01/250/back/bright/04.png",
                              "source/mackerel#3/stage01/250/back/bright/05.png"]]

mackerel3_250_back_dark = [["source/mackerel#3/stage00/250/back/dark/01.png",
                            "source/mackerel#3/stage00/250/back/dark/02.png",
                            "source/mackerel#3/stage00/250/back/dark/03.png",
                            "source/mackerel#3/stage00/250/back/dark/04.png",
                            "source/mackerel#3/stage00/250/back/dark/05.png"],
                           ["source/mackerel#3/stage01/250/back/dark/01.png",
                            "source/mackerel#3/stage01/250/back/dark/02.png",
                            "source/mackerel#3/stage01/250/back/dark/03.png",
                            "source/mackerel#3/stage01/250/back/dark/04.png",
                            "source/mackerel#3/stage01/250/back/dark/05.png"]]

mackerel3_350_back_bright = [["source/mackerel#3/stage00/350/back/bright/01.png",
                              "source/mackerel#3/stage00/350/back/bright/02.png",
                              "source/mackerel#3/stage00/350/back/bright/03.png",
                              "source/mackerel#3/stage00/350/back/bright/04.png",
                              "source/mackerel#3/stage00/350/back/bright/05.png"],
                             ["source/mackerel#3/stage01/350/back/bright/01.png",
                              "source/mackerel#3/stage01/350/back/bright/02.png",
                              "source/mackerel#3/stage01/350/back/bright/03.png",
                              "source/mackerel#3/stage01/350/back/bright/04.png",
                              "source/mackerel#3/stage01/350/back/bright/05.png"]]

mackerel3_350_back_dark = [["source/mackerel#3/stage00/350/back/dark/01.png",
                            "source/mackerel#3/stage00/350/back/dark/02.png",
                            "source/mackerel#3/stage00/350/back/dark/03.png",
                            "source/mackerel#3/stage00/350/back/dark/04.png",
                            "source/mackerel#3/stage00/350/back/dark/05.png"],
                           ["source/mackerel#3/stage01/350/back/dark/01.png",
                            "source/mackerel#3/stage01/350/back/dark/02.png",
                            "source/mackerel#3/stage01/350/back/dark/03.png",
                            "source/mackerel#3/stage01/350/back/dark/04.png",
                            "source/mackerel#3/stage01/350/back/dark/05.png"]]

mackerel3_250_stomach_bright = [["source/mackerel#3/stage00/250/stomach/bright/01.png",
                                 "source/mackerel#3/stage00/250/stomach/bright/02.png",
                                 "source/mackerel#3/stage00/250/stomach/bright/03.png",
                                 "source/mackerel#3/stage00/250/stomach/bright/04.png",
                                 "source/mackerel#3/stage00/250/stomach/bright/05.png"],
                                ["source/mackerel#3/stage01/250/stomach/bright/01.png",
                                 "source/mackerel#3/stage01/250/stomach/bright/02.png",
                                 "source/mackerel#3/stage01/250/stomach/bright/03.png",
                                 "source/mackerel#3/stage01/250/stomach/bright/04.png",
                                 "source/mackerel#3/stage01/250/stomach/bright/05.png"]]

mackerel3_250_stomach_dark = [["source/mackerel#3/stage00/250/stomach/dark/01.png",
                               "source/mackerel#3/stage00/250/stomach/dark/02.png",
                               "source/mackerel#3/stage00/250/stomach/dark/03.png",
                               "source/mackerel#3/stage00/250/stomach/dark/04.png",
                               "source/mackerel#3/stage00/250/stomach/dark/05.png"],
                              ["source/mackerel#3/stage01/250/stomach/dark/01.png",
                               "source/mackerel#3/stage01/250/stomach/dark/02.png",
                               "source/mackerel#3/stage01/250/stomach/dark/03.png",
                               "source/mackerel#3/stage01/250/stomach/dark/04.png",
                               "source/mackerel#3/stage01/250/stomach/dark/05.png"]]

mackerel3_350_stomach_bright = [["source/mackerel#3/stage00/350/stomach/bright/01.png",
                                 "source/mackerel#3/stage00/350/stomach/bright/02.png",
                                 "source/mackerel#3/stage00/350/stomach/bright/03.png",
                                 "source/mackerel#3/stage00/350/stomach/bright/04.png",
                                 "source/mackerel#3/stage00/350/stomach/bright/05.png"],
                                ["source/mackerel#3/stage01/350/stomach/bright/01.png",
                                 "source/mackerel#3/stage01/350/stomach/bright/02.png",
                                 "source/mackerel#3/stage01/350/stomach/bright/03.png",
                                 "source/mackerel#3/stage01/350/stomach/bright/04.png",
                                 "source/mackerel#3/stage01/350/stomach/bright/05.png"]]

mackerel3_350_stomach_dark = [["source/mackerel#3/stage00/350/stomach/dark/01.png",
                               "source/mackerel#3/stage00/350/stomach/dark/02.png",
                               "source/mackerel#3/stage00/350/stomach/dark/03.png",
                               "source/mackerel#3/stage00/350/stomach/dark/04.png",
                               "source/mackerel#3/stage00/350/stomach/dark/05.png"],
                              ["source/mackerel#3/stage01/350/stomach/dark/01.png",
                               "source/mackerel#3/stage01/350/stomach/dark/02.png",
                               "source/mackerel#3/stage01/350/stomach/dark/03.png",
                               "source/mackerel#3/stage01/350/stomach/dark/04.png",
                               "source/mackerel#3/stage01/350/stomach/dark/05.png"]]
